#!/bin/sh

export ZDOTDIR=$HOME/.config/zsh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

feh --bg-fill ~/Downloads/SK-A-1892.jpg
brightnessctl -d 'intel_backlight' set 100%
setxkbmap -option 'caps:ctrl_modifier';xcape -e 'Caps_Lock=Escape'
xset r rate 250 30 # https://wiki.archlinux.org/title/Xorg/Keyboard_configuration
eval `ssh-agent`

sxhkd &
clipit &
unclutter &
udiskie &
picom &
dwmblocks&
exec dwm
