#!/bin/bash

# NOTICE:
# Adapted from Gary Bernhardt's script at https://github.com/garybernhardt/dotfiles/blob/main/.githelpers
#
# Log output:
#
# * 51c333e    (12 days)    <Ruben S. Garcia>   add conjure
#
# The time massaging regexes start with ^[^<]* because that ensures that they
# only operate before the first "<". That "<" will be the beginning of the
# author name, ensuring that we don't destroy anything in the commit message
# that looks like time.
#
# The log format uses } characters between each field, and `column` is later
# used to split on them. A } in the commit subject or any other field will
# break this.
#

HASH="%C(yellow)%h%C(reset)"
RELATIVE_DATE="%C(green bold)(%ar)%C(reset)"
AUTHOR="%C(blue bold)<%an>%C(reset)"
REFS="%C(red)%d%C(reset)"
SUBJECT="%s"

FORMAT="$HASH}$RELATIVE_DATE}$AUTHOR}$REFS $SUBJECT"

pretty_git_log() {
	git log --graph --pretty="format:$FORMAT" --no-show-signature --color=always $* | pretty_git_format | git_page_maybe
}

pretty_git_format() {
	# Replace (2 years ago) with (2 years)
	sed -Ee 's/(^[^<]*) ago\)/\1)/' |
		# Replace (2 years, 5 months) with (2 years)
		sed -Ee 's/(^[^<]*), [[:digit:]]+ .*months?\)/\1)/' |
		# Line columns up based on } delimiter
		column -s '}' -t
}

git_page_maybe() {
	# Page only if we're asked to.
	if [ -n "$GIT_NO_PAGER" ]; then
		cat
	else
		# Page only if needed.
		less --quit-if-one-screen --no-init --RAW-CONTROL-CHARS --chop-long-lines
	fi
}
