[global/wm]
margin-botton = 0

include-file = ~/.config/polybar/colors.ini
include-file = ~/.config/polybar/modules.ini

[bar/mybar]
monitor = ${env:MONITOR:}
width = 100%
height = 30
fixed-center = true

background = ${color.background}
foreground = ${color.foreground}

line-size = 2
line-color = ${color.primary}

radius-top = 0.0
radius-bottom = 0.0

border-size = 0
; border-color = #00000000

padding = 0
; padding-left = 0
; padding-right = 2

; Values applied to all borders
; Individual side values can be defined using:
;   border-{left,top,right,bottom}-size
;   border-{left,top,right,bottom}-color
; The top and bottom borders are added to the bar height, so the effective
; window height is:
;   height + border-top-size + border-bottom-size
; Meanwhile the effective window width is defined entirely by the width key and
; the border is placed withing this area. So you effectively only have the
; following horizontal space on the bar:
;   width - border-right-size - border-left-size
border-bottom-size = 0
border-bottom-color = ${color.primary}

; Number of spaces to add before/after each module
; Individual side values can be defined using:
;   module-margin-{left,right}
module-margin-left = 1.5
module-margin-right = 1.5

; module-margin-left = 1
; module-margin-right = 2
tray-position = right
; tray-background =${color.background}
dim-value = 1.0

; font-0 = fixed:pixelsize=10;1
; font-1 = unifont:fontformat=truetype:size=8:antialias=false;0
; font-2 = siji:pixelsize=20;3
font-0 = "Iosevka Nerd Font:size=10;2"
font-1 = "feather:size=12;2"

;Modules
modules-right = filesystem battery xkeyboard cpu memory wlan date
modules-center = xwindow
modules-left = i3
