[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

format = <label-layout> <label-indicator>
format-prefix = " "
; format = <label>
; format-prefix = " "
; format-prefix-foreground = ${colors.foreground-alt}
; format-prefix-underline = ${colors.secondary}

label-layout = %layout%
; label-layout-underline = ${colors.secondary}

label-indicator-padding = 2
label-indicator-margin = 1
; label-indicator-background = ${colors.secondary}
; label-indicator-underline = ${colors.secondary}

[module/filesystem]
type = internal/fs
interval = 15

mount-0 = /home
mount-1 = /

label-mounted =  %mountpoint%%{F-}: %percentage_used%%
label-unmounted = %mountpoint% not mounted
; label-unmounted-foreground = ${colors.foreground-alt}

[module/date]
type = internal/date
; interval = 5

date = "%d.%m.%Y"
; date-alt = " %d-%m-%Y"

; time = %H:%M
; time-alt = %H:%M:%S

format-prefix = " "
; format-prefix-foreground = ${colors.foreground-alt}
; format-underline = #0a6cf5

; label = %date% %time%

; Seconds to sleep between updates
interval = 1.0

; See "http://en.cppreference.com/w/cpp/io/manip/put_time" for details on how to format the date string
; NOTE: if you want to use syntax tags here you need to use %%{...}
;;date = %Y-%m-%d%

; Optional time format
time = "%H:%M"

; if `date-alt` or `time-alt` is defined, clicking
; the module will toggle between formats
;;date-alt = %A, %d %B %Y
time-alt = " %a, %d %b %Y"

; Available tags:
;   <label> (default)
format = <label>

; Available tokens:
;   %date%
;   %time%
; Default: %date%
label = %date% %time%

[module/i3]
type = internal/i3
format = <label-state> <label-mode>
index-sort = true
wrapping-scroll = false

; Only show workspaces on the same output as the bar
; Useful when more than 1 monitor
pin-workspaces = true

label-mode-padding = 2
label-mode-foreground = #000
label-mode-background = ${color.primary}

; focused = Active workspace on focused monitor
label-focused = %index%
; #00ff1a
label-focused-foreground = ${color.label-focused-foreground}
label-focused-background = ${color.label-focused-background}
label-focused-underline = ${color.label-focused-underline}

; unfocused = Inactive workspace on any monitor
label-unfocused = %index%

; visible = Active workspace on unfocused monitor
label-visible = %index%
label-visible-background = ${self.label-focused-background}
label-visible-overline = ${self.label-focused-underline}
label-visible-padding = ${self.label-focused-padding}

; urgent = Workspace with urgency hint set
label-urgent = %index%
label-urgent-foreground = #fff
label-urgent-background = ${color.alert}

label-focused-padding = 2
label-unfocused-padding = 2
label-urgent-padding = 2

; Separator in between workspaces
label-separator =

[module/cpu]
type = internal/cpu
; interval = 2
; format-prefix = " "
; label = %percentage:2%%

; Seconds to sleep between updates
; Default: 1
interval = 0.5

; Available tags:
;   <label> (default)
;   <bar-load>
;   <ramp-load>
;   <ramp-coreload>
;;format = <label> <ramp-coreload>
format = <label>
format-prefix = " "
; format-prefix-foreground = ${colors.foreground-alt}
; format-underline = #f90000

; Available tokens:
;   %percentage% (default) - total cpu load averaged over all cores
;   %percentage-sum% - Cumulative load on all cores
;   %percentage-cores% - load percentage for each core
;   %percentage-core[1-9]% - load percentage for specific core
label = "%percentage-sum:2%%"

[module/memory]
type = internal/memory
interval = 1
format = <label>
format-prefix = " "
label = %gb_used% / %gb_total%

[module/wlan]
type = internal/network
interface = wlo1
interval = 3.0

; format-connected = <ramp-signal> <label-connected>
; format-connected-underline = #9f78e1
label-connected = %essid% %netspeed%
label-connected-foreground = #00ff1a

; Default: (none)
label-disconnected = not connected
label-disconnected-foreground = #ff123f

[module/battery]
type = internal/battery

; This is useful in case the battery never reports 100% charge
full-at = 99

; At this percent we should be careful
low-at = 10

; Use the following command to list batteries and adapters:
; $ ls -1 /sys/class/power_supply/
battery = BAT0
adapter = ADP1

; If an inotify event haven't been reported in this many
; seconds, manually poll for new values.
;
; Needed as a fallback for systems that don't report events
; on sysfs/procfs.
;
; Disable polling by setting the interval to 0.
;
; Default: 5
poll-interval = 2

; see "man date" for details on how to format the time string
; NOTE: if you want to use syntax tags here you need to use %%{...}
; Default: %H:%M:%S
time-format = %H:%M

; Available tags:
;   <label-charging> (default)
;   <bar-capacity>
;   <ramp-capacity>
;   <animation-charging>
format-charging = <animation-charging>   <label-charging>
; format-charging-prefix = " "

; Available tags:
;   <label-discharging> (default)
;   <bar-capacity>
;   <ramp-capacity>
;   <animation-discharging>
format-discharging = <animation-discharging>   <label-discharging>
; format-discharging-prefix = " "

; Format used when battery level drops to low-at
; If not defined, format-discharging is used instead.
; Available tags:
;   <label-low>
;   <animation-low>
;   <bar-capacity>
;   <ramp-capacity>
; New in version 3.6.0
format-low = <animation-low>   <label-low>

; Available tags:
;   <label-full> (default)
;   <bar-capacity>
;   <ramp-capacity>
format-full = <label-full>
format-full-prefix = "  "

; Available tokens:
;   %percentage% (default)
;   %time%
;   %consumption% (shows current charge rate in watts)
label-charging = %percentage%% %time%

; Available tokens:
;   %percentage% (default)
;   %time%
;   %consumption% (shows current discharge rate in watts)
label-discharging = %percentage%% %time%

; Available tokens:
;   %percentage% (default)
label-full = %percentage%%

; Available tokens:
;   %percentage% (default) - is set to 100 if full-at is reached
;   %percentage_raw%
;   %time%
;   %consumption% (shows current discharge rate in watts)
; New in version 3.6.0
label-low = %time%

; Only applies if <bar-capacity> is used
;bar-capacity-width = 10

; Battery glyphs
no-charge = 
one-quarter-charge = 
two-quarter-charge = 
three-quarter-charge = 
full-charge = 

; Only applies if <animation-charging> is used
animation-charging-0 = ${self.one-quarter-charge}
animation-charging-1 = ${self.two-quarter-charge}
animation-charging-2 = ${self.three-quarter-charge}
animation-charging-3 = ${self.full-charge}
; Framerate in milliseconds
animation-charging-framerate = 750

; Only applies if <animation-discharging> is used
animation-discharging-0 = ${self.three-quarter-charge}
animation-discharging-1 = ${self.two-quarter-charge}
animation-discharging-2 = ${self.one-quarter-charge}
animation-discharging-3 = ${self.no-charge}
;; Framerate in milliseconds
animation-discharging-framerate = 900

; Only applies if <animation-low> is used
animation-low-0 = ${self.one-quarter-charge}
animation-low-1 = ${self.no-charge}
;; Framerate in milliseconds
animation-low-framerate = 200

[module/pulseaudio]
type = internal/pulseaudio

; Sink to be used, if it exists (find using `pacmd list-sinks`, name field)
; If not, uses default sink
; sink = alsa_output.pci-0000_12_00.3.analog-stereo

; Use PA_VOLUME_UI_MAX (~153%) if true, or PA_VOLUME_NORM (100%) if false
; Default: true
use-ui-max = false

; Interval for volume increase/decrease (in percent points)
; Default: 5
interval = 5

; Available tags:
;   <label-volume> (default)
;   <ramp-volume>
;   <bar-volume>
format-volume = <ramp-volume> <label-volume>

; Available tags:
;   <label-muted> (default)
;   <ramp-volume>
;   <bar-volume>
;format-muted = <label-muted>

; Available tokens:
;   %percentage% (default)
;   %decibels%
;label-volume = %percentage%%

; Available tokens:
;   %percentage% (default)
;   %decibels%
label-muted = Muted 
label-muted-foreground = #666

; Only applies if <ramp-volume> is used

ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 

; Right and Middle click
click-right = pavucontrol
; click-middle = 

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_


; vim:ft=dosini
