#!/bin/zsh
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

. /opt/asdf-vm/asdf.sh
export DOTFILES="$HOME/dotfiles"
export PROJECTS="$HOME/code"

typeset -U config_files
typeset -U fns
config_files=($DOTFILES/*/*.zsh)
fns=($DOTFILES/*/functions/*.zsh)

# load antibody plugins
source ~/.zsh_plugins.sh

# load everything but the path and completion files
for file in ${${config_files:#*/path.zsh}:#*/completion.zsh}; do
  source "$file"
done

autoload -Uz compinit
for dump in ~/.zcompdump(N.mh+24); do
  compinit
done
compinit -C

# load every completion after autocomplete loads
for file in ${(M)config_files:#*/completion.zsh}; do
  source "$file"
done

# load functions inside functions directory
for file in ${fns}; do
  source "$file"
done

unset config_files
unset fns

# Init fasd
eval "$(fasd --init auto)"

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/home/sigfried/.sdkman"
[[ -s "/home/sigfried/.sdkman/bin/sdkman-init.sh" ]] && source "/home/sigfried/.sdkman/bin/sdkman-init.sh"

source /home/sigfried/.profile
source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
