#!/bin/zsh
export DOTFILES="$HOME/dotfiles"
export PROJECTS="$HOME/code"

typeset -U config_files
typeset -U fns
config_files=($DOTFILES/*/*.zsh)
fns=($DOTFILES/*/functions/*.zsh)

# load antibody plugins
source ~/.zsh_plugins.sh

# load everything but the path and completion files
for file in ${${config_files:#*/path.zsh}:#*/completion.zsh}; do
  source "$file"
done

# NVM's config
# Should be place before autocompletions
export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

autoload -Uz compinit
for dump in ~/.zcompdump(N.mh+24); do
  compinit
done
compinit -C

# load every completion after autocomplete loads
for file in ${(M)config_files:#*/completion.zsh}; do
  source "$file"
done

# load functions inside functions directory
for file in ${fns}; do
  source "$file"
done

unset config_files
unset fns

# Init fasd
eval "$(fasd --init auto)"

# Init starship prompt
eval "$(starship init zsh)"

# Init pyenv and pyenv-virtualenv
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"


#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/home/sigfried/.sdkman"
[[ -s "/home/sigfried/.sdkman/bin/sdkman-init.sh" ]] && source "/home/sigfried/.sdkman/bin/sdkman-init.sh"
